CREATE OR REPLACE PACKAGE BODY SCOTT.PKG_DEMO AS

    FUNCTION SUMA( N1 IN NUMBER, N2 IN NUMBER ) RETURN NUMBER
    IS
        SUMA NUMBER;
    BEGIN
        SUMA := N1 + N2;
        RETURN SUMA;
    END;

END PKG_DEMO;