CREATE OR REPLACE TRIGGER SCOTT.TRG1
AFTER INSERT OR DELETE OR UPDATE ON SCOTT.EMP

BEGIN
  IF INSERTING THEN 
    DBMS_OUTPUT.PUT_LINE('NUEVO EMPLEADO SE HA INSERTADO');
  ELSIF UPDATING THEN
    DBMS_OUTPUT.PUT_LINE('UN EMPLEADO SE HA MODIFICADO');
  ELSIF DELETING THEN
    DBMS_OUTPUT.PUT_LINE('UN EMPLEADO SE HA ELIMINADO');
  END IF;
END;