CREATE OR REPLACE PROCEDURE SCOTT.UPDATE_SALEMP
(COD SCOTT.EMP.EMPNO%TYPE,SALARIO SCOTT.EMP.SAL%TYPE)
IS
    CONT NUMBER;
BEGIN
    SELECT COUNT(*) INTO CONT
    FROM SCOTT.EMP
    WHERE EMPNO=COD;
    
    IF (CONT=0) THEN
        RAISE_APPLICATION_ERROR(-20000, 'NO EXISTE CÓDIGO DEL EMPLEADO');
    END IF;
    
    UPDATE SCOTT.EMP
    SET SAL=SALARIO
    WHERE EMPNO=COD;
    COMMIT; 
    DBMS_OUTPUT.PUT_LINE('PROCESO OK.');
    DBMS_OUTPUT.PUT_LINE('EL SALARIO DEL EMPLEADO NRO:'||COD || ' SE CAMBIÓ A: '||SALARIO);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR NRO ORA: '|| TO_CHAR(SQLCODE));
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

CALL SCOTT.UPDATE_SALEMP(7934,55555);

CALL SCOTT.UPDATE_SALEMP(793455,5555);

