CREATE OR REPLACE PROCEDURE SCOTT.PR_DATOS_EMP
( P_CODIGO EMP.EMPNO%TYPE)
IS
    TYPE REG IS RECORD(
        NOMBRE EMP.ENAME%TYPE,
        SALARIO EMP.SAL%TYPE
    );
    R REG;
BEGIN
    SELECT ENAME, SAL INTO R
    FROM EMP WHERE EMPNO = P_CODIGO;
    DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || R.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('SALARIO: ' || R.SALARIO);
END;

CALL SCOTT.PR_DATOS_EMP( 7698 );


        