
CREATE OR REPLACE PROCEDURE PR_15
IS
    CURSOR C_EMP IS SELECT * FROM EMP;
    R EMP%ROWTYPE;
BEGIN
    OPEN C_EMP;
    LOOP    
        FETCH C_EMP INTO R;
        EXIT WHEN C_EMP%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(R.EMPNO || R.ENAME);        
    END LOOP;
    CLOSE C_EMP;
END;

SET SERVEROUTPUT ON

CALL PR_15();