CREATE OR REPLACE PROCEDURE PR_17
IS
    CURSOR C_DEPT IS SELECT * FROM DEPT;
    EMPS NUMBER;
    PLANILLA NUMBER;
    CAD VARCHAR2(100);
BEGIN
    FOR R IN C_DEPT LOOP
        SELECT COUNT(*), SUM(NVL(SAL,0)) INTO EMPS, PLANILLA
        FROM EMP 
        WHERE DEPTNO = R.DEPTNO;
        
        CAD:= R.DEPTNO || ' - ' || EMPS || ' - ' || NVL(PLANILLA,0);
        DBMS_OUTPUT.PUT_LINE(CAD);        
    END LOOP;    
END;

SET SERVEROUTPUT ON

CALL PR_17();